#!/bin/bash

set -euo pipefail

cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

npm install --silent
npx axium upgrade --git --allow-breaking
git push

if [[ -n "$1" ]]; then
	echo "--- updating remote ---"
	ssh -t "$1" ./axium-up
	echo ""
fi
