#!/bin/bash

set -euo pipefail

root="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

packages=("calendar" "client" "contacts" "core" "notes" "server" "storage" "tasks" "sysadmin" "email")

build=true
args=()
npm_install_opts=()

for arg in "$@"; do
	case "$arg" in
		"--build")
			build=true
			;;
		"--no-build" | "-b")
			build=false
			;;
		"--foreground-scripts" | "-f")
			npm_install_opts+=("--foreground-scripts")
			;;
		*)
			args+=("$arg")
			;;
	esac
done

postinstall() {
	npm run clean
	npx axium link
	npx tsc -p "$root/src/tsconfig.json" --noEmit
	if [ "$build" = true ]; then
		npx axium build
	fi
}

sub="${args[0]:-help}"

case "$sub" in
	"local")
		dir="../axium/packages"
		install_mode="--no-save"

		for arg in "${args[@]:1}"; do
			case "$arg" in
				"--save")
					install_mode=""
					;;
				--*)
					echo "Unknown option for local: $arg" >&2
					exit 1
					;;
				*)
					dir="$arg"
					;;
			esac
		done

		pkgs=("${packages[@]/#/$dir/}")
		if [ -n "$install_mode" ]; then
			npm install "${npm_install_opts[@]}" "$install_mode" "${pkgs[@]}"
		else
			npm install "${npm_install_opts[@]}" "${pkgs[@]}"
		fi
		postinstall
		;;
	"latest")
		pkgs=("${packages[@]/#/@axium/}")
		npm install "${npm_install_opts[@]}" "${pkgs[@]/%/@latest}"
		postinstall
		;;
	"help" | *)
		cat << EOF
Usage: $0 [options] <command>

Options:
    --[no-]build, -b          Whether to run a build after installing (-b disables it)
    --foreground-scripts, -f  Run npm install scripts in the foreground

Commands:
    local [directory] [--save]  Install Axium packages from a local directory. Defaults to ../axium/packages.
    latest                      Install the latest versions of Axium packages
    help                        Show this help message
EOF
		if [ "$sub" != "help" ]; then
			exit 1
		fi
		;;
esac 
