#!/bin/bash

set -euo pipefail

root="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

packages=("calendar" "client" "contacts" "core" "notes" "server" "storage" "tasks")

postinstall() {
	npm run clean
	npx axium link
	npx tsc -p "$root/src/tsconfig.json" --noEmit
	npx axium build
}

sub="${1:-help}"

case "$sub" in
	"local")
		dir="${2:-"../axium"}"
		npm install --no-save ${packages[@]/#/$dir/}
		postinstall
		;;
	"latest")
		pkgs=("${packages[@]/#/@axium/}")
		npm install "${pkgs[@]/%/@latest}"
		postinstall
		;;
	"help" | *)
		cat << EOF
Usage: $0 <command>

Commands:
    local [directory]  Install Axium packages from a local directory. Defaults to ../axium
    latest             Install the latest versions of Axium packages
    help               Show this help message
EOF
		if [ "$sub" != "help" ]; then
			exit 1
		fi
		;;
esac 
